package archive

import (
	"encoding/xml"
	"fmt"
	"time"

	"github.com/omarys/labrador/internal/domain"
)

// ComicInfo represents the ComicRack / ComicInfo.xml schema specification.
type ComicInfo struct {
	XMLName   xml.Name `xml:"ComicInfo"`
	Title     string   `xml:"Title,omitempty"`
	Series    string   `xml:"Series,omitempty"`
	Number    string   `xml:"Number,omitempty"`
	Summary   string   `xml:"Summary,omitempty"`
	PageCount int      `xml:"PageCount"`
	Year      int      `xml:"Year,omitempty"`
	Month     int      `xml:"Month,omitempty"`
	Day       int      `xml:"Day,omitempty"`
	Web       string   `xml:"Web,omitempty"`
	Manga     string   `xml:"Manga,omitempty"`
	Notes     string   `xml:"Notes,omitempty"`
}

// GenerateComicInfo builds the XML bytes for a given series, chapter, and page count.
func GenerateComicInfo(series domain.Series, chapter domain.Chapter, pageCount int) ([]byte, error) {
	now := time.Now()
	numberStr := ""
	if chapter.Number != nil {
		numberStr = fmt.Sprintf("%g", *chapter.Number)
	} else if chapter.Title != "" {
		numberStr = chapter.Title
	}

	info := ComicInfo{
		Title:     chapter.Title,
		Series:    series.Title,
		Number:    numberStr,
		Summary:   chapter.Title,
		PageCount: pageCount,
		Year:      now.Year(),
		Month:     int(now.Month()),
		Day:       now.Day(),
		Web:       chapter.URL,
		Manga:     "YesAndRightToLeft",
		Notes:     "Generated by Labrador",
	}

	data, err := xml.MarshalIndent(info, "", " ")
	if err != nil {
		return nil, fmt.Errorf("marshaling comicinfo.xml: %w", err)
	}

	header := []byte(xml.Header)
	return append(header, data...), nil
}
